name: Go Tests

on:
  push:
    branches: [ "main" ]   # or your default branch
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.24.5"      

    - name: Run Plugin Tests
      run: |
        go mod tidy
        go test ./tests      
